# Generated by Django 2.2.6 on 2019-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
